### ISSUE TITLE
[BUG]Products not displayed on Store page

### ISSUE THREAD

**Issue by Smartmind12** [pankod/refine#2697] opened 2022-10-11 03:39 UTC
**Describe the bug**
Products like Cap, Coasters and Stickers are not displayed in the Front Store page. Making users think that only limited items are available in the store, which is not the case!

**To Reproduce**
1. Go to '(https://store.refine.dev/)'
2. Checkout the page
3. See error

**Expected behavior**
Adding these products to the Front Store Page so that users/customers can view the variety of products Refine has to offer.

**Screenshots**
![Screenshot 2022-10-11 at 8 59 32 AM](https://user-images.githubusercontent.com/91927689/194991177-061ee00e-eebf-4cb4-a1cf-699a82f3ef7f.png)

**Additional context**
Kindly assignee me this issue as i would like to work on it!

**Comment by aliemir** [comment] 2022-10-11 06:58
Thank you for the issue @Smartmind12 🙏 , this is actually by design, we don't want to show all the products since we're expecting to have a lot more swag to be added in the following months, it's not going to look good to try to show all of them on the home page. Closing this for now but let us know if you see any other errors in the https://store.refine.dev 🚀

**Closed by aliemir** 2022-10-11 06:58 UTC
Labels: bug
