### ISSUE TITLE
[BUG] It will get a undefined error when startup

### ISSUE THREAD

**Issue by loseleo** [pankod/refine#2608] opened 2022-10-01 02:02 UTC
**Describe the bug**
I copied the code  https://github.com/pankod/refine/tree/master/examples/fineFoods/admin/antd
then startup ,it will have an error undefined in any pages.

By the way ,this demo may use "react-scripts": "^4.0.0", for source-map warning
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4935557/193378750-933ab8bf-aa15-4811-8754-f304554671d4.png)
**Desktop (please complete the following information):**
 - OS: MacOS
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**

**Comment by omeraplak** [comment] 2022-10-01 06:25
Hey @loseleo 👋,
Thank you for contacting us. Let's see what we can do

**Comment by chavda-bhavik** [comment] 2022-10-06 03:06
@omeraplak I would like to give it a try. I'm new to refine, can you give me some guidelines?

**Comment by omeraplak** [comment] 2022-10-06 13:02
Hey @chavda-bhavik ,
Thank you for your interest! My guess is that when AuthProvider is defined, the `checkAuth` function `Promise.reject()` for unauthorized users.

https://github.com/pankod/refine/blob/next/packages/core/src/contexts/auth/index.tsx#L62

You can reproduce the issue with this example.

https://refine.dev/docs/examples/authentication/antd/

**Comment by chavda-bhavik** [comment] 2022-10-07 02:22
Thanks, @omeraplak For a clear explanation, I got your point. I see that everywhere we're using `Promise.reject()` to indicate the user is Unauthenticated. 

So I think we have to remove logging for the unauthenticated user from `refine/core` so that the `checkAuth` function does not log in console when the user is `Unauthenticated (Promise.reject)`. Am I on right track?

**Comment by omeraplak** [comment] 2022-10-07 05:28
Yes, you are right @chavda-bhavik

**Comment by aliemir** [comment] 2022-10-12 08:59
Hey @chavda-bhavik, thank you for raising this issue! Let me explain the process here a bit further. 

When you pass the `authProvider` prop to `<Refine/>` component, authentication becomes a part of the routing process (router providers use the `useAuthenticated` hook for this). At the initial rendering, router provider tries to determine the initial route which includes the authentication check. Therefore, `checkAuth` will be and required to be called at the initial render. 

About the logging issue, this is actually not on refine's nor your end, it's coming from the `@tanstack/react-query` which logs the failed queries/mutations on development mode for debugging purposes. It's okay to leave them unattended since react-query will not log failed queries on production mode. 

About the `console.error` printing `undefined`, its because `Promise.reject()` being called with no parameters (same issue happens in the example shared by @omeraplak). You can do something like `Promise.reject("Not Authenticated")` to be able to separate this error from the actual errors/logs in your app.

If this is still an issue for you in the development mode, you can easily get rid of it by providing a custom logger to the `queryClient`. 

Here's an example for a custom logger with muted `checkAuth` 😅 

Assuming we're rejecting at `checkAuth` like this; `Promise.reject("Not Authenticated")`

```tsx
<Refine
    options={{
        reactQuery: {
            clientConfig: {
                logger: {
                    log: console.log,
                    warn: console.warn,
                    error: function (...args) {
                        if (args[0] !== "Not Authenticated") {
                            console.error(...args);
                        }
                    },
                },
            },
        },
    }}
/>
```

We can provide a default logger to silence react-query error logs but I think this is not a good practice to hide external logs from the user. 🤔 

Thanks again for the issue, I hope the explanation is clear. Closing the issue for now, please do not hesitate to reach out in any cases.

**Closed by aliemir** 2022-10-12 08:59 UTC
Labels: bug, hacktoberfest
