### ISSUE TITLE
[BUG] Error after upgrade

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2232] opened 2022-07-27 13:35 UTC
Hi everyone,

I started getting this error when I upgraded to these versions the my project;
` "@pankod/refine-antd": "^3.33.2",
        "@pankod/refine-core": "^3.50.0",`

full list is;

`{
"dependencies": {
        "@pankod/refine-antd": "^3.33.2",
        "@pankod/refine-core": "^3.50.0",
        "@pankod/refine-graphql": "^4.5.0",
        "@pankod/refine-react-router-v6": "^3.29.0",
        "@pankod/refine-simple-rest": "^3.25.6",
        "@testing-library/jest-dom": "^5.12.0",
        "@testing-library/react": "^11.2.6",
        "@testing-library/user-event": "^12.8.3",
        "@types/jest": "^26.0.23",
        "camelcase": "^7.0.0",
        "graphql": "^15.5.3",
        "graphql-request": "^4.3.0",
        "i18next": "^20.1.0",
        "i18next-browser-languagedetector": "^6.1.1",
        "i18next-xhr-backend": "^3.2.2",
        "leaflet": "^1.8.0",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-i18next": "^11.8.11",
        "react-leaflet": "^4.0.1",
        "react-leaflet-google-layer": "^2.0.7",
        "react-scripts": "^5.0.0",
        "web-vitals": "^1.1.1"
    },
}`

`utils.js:186 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'FiberRootNode'
    |     property 'containerInfo' -> object with constructor 'HTMLDivElement'
    --- property '__reactContainer$nnm0w6la9' closes the circle
    at JSON.stringify (<anonymous>)
    at stableValueHash (utils.js:186:1)
    at hashQueryKey (utils.js:179:1)
    at hashQueryKeyByOptions (utils.js:171:1)
    at QueryClient.defaultQueryOptions (queryClient.js:324:1)
    at QueryClient.defaultQueryObserverOptions (queryClient.js:331:1)
    at useBaseQuery (useBaseQuery.js:14:1)
    at useQuery (useQuery.js:7:1)
    at ir (index.ts:25:1)
    at Hn (index.tsx:18:1)
stableValueHash @ utils.js:186
hashQueryKey @ utils.js:179
hashQueryKeyByOptions @ utils.js:171
defaultQueryOptions @ queryClient.js:324
defaultQueryObserverOptions @ queryClient.js:331
useBaseQuery @ useBaseQuery.js:14
useQuery @ useQuery.js:7
ir @ index.ts:25
Hn @ index.tsx:18
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
(anonymous) @ notifyManager.js:75
Promise.then (async)
scheduleMicrotask @ utils.js:322
flush @ notifyManager.js:74
batch @ notifyManager.js:30
dispatch @ query.js:392
setData @ query.js:85
onSuccess @ query.js:336
resolve @ retryer.js:58
Promise.then (async)
run @ retryer.js:116
Retryer @ retryer.js:156
fetch @ query.js:332
executeFetch @ queryObserver.js:199
onSubscribe @ queryObserver.js:40
subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react-dom.development.js:20085 The above error occurred in the <Hn> component:

    at Hn (http://localhost:3000/static/js/bundle.js:76863:15)
    at v (http://localhost:3000/static/js/bundle.js:78528:12)
    at Outlet (http://localhost:3000/static/js/bundle.js:253508:26)
    at div
    at main
    at http://localhost:3000/static/js/bundle.js:90924:25
    at http://localhost:3000/static/js/bundle.js:90903:66
    at section
    at http://localhost:3000/static/js/bundle.js:90940:63
    at http://localhost:3000/static/js/bundle.js:90903:66
    at section
    at http://localhost:3000/static/js/bundle.js:90940:63
    at http://localhost:3000/static/js/bundle.js:90903:66
    at Layout (http://localhost:3000/static/js/bundle.js:853:5)
    at Vn (http://localhost:3000/static/js/bundle.js:76764:15)
    at Routes (http://localhost:3000/static/js/bundle.js:253600:5)
    at R (http://localhost:3000/static/js/bundle.js:78647:71)
    at Router (http://localhost:3000/static/js/bundle.js:253533:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:252343:5)
    at B (http://localhost:3000/static/js/bundle.js:78744:15)
    at Zt (http://localhost:3000/static/js/bundle.js:75215:15)
    at Ot (http://localhost:3000/static/js/bundle.js:74915:19)
    at ct (http://localhost:3000/static/js/bundle.js:73769:15)
    at dr (http://localhost:3000/static/js/bundle.js:76210:13)
    at ar (http://localhost:3000/static/js/bundle.js:75882:10)
    at jt (http://localhost:3000/static/js/bundle.js:75154:15)
    at qt (http://localhost:3000/static/js/bundle.js:75039:16)
    at nr (http://localhost:3000/static/js/bundle.js:75836:15)
    at Wt (http://localhost:3000/static/js/bundle.js:74880:19)
    at Ht (http://localhost:3000/static/js/bundle.js:74849:15)
    at Mt (http://localhost:3000/static/js/bundle.js:73172:15)
    at Jt (http://localhost:3000/static/js/bundle.js:75114:11)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:250837:21)
    at Qn (http://localhost:3000/static/js/bundle.js:76614:19)
    at App (http://localhost:3000/static/js/bundle.js:113:69)
    at Suspense

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
(anonymous) @ notifyManager.js:75
Promise.then (async)
scheduleMicrotask @ utils.js:322
flush @ notifyManager.js:74
batch @ notifyManager.js:30
dispatch @ query.js:392
setData @ query.js:85
onSuccess @ query.js:336
resolve @ retryer.js:58
Promise.then (async)
run @ retryer.js:116
Retryer @ retryer.js:156
fetch @ query.js:332
executeFetch @ queryObserver.js:199
onSubscribe @ queryObserver.js:40
subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
utils.js:186 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'FiberRootNode'
    |     property 'containerInfo' -> object with constructor 'HTMLDivElement'
    --- property '__reactContainer$nnm0w6la9' closes the circle
    at JSON.stringify (<anonymous>)
    at stableValueHash (utils.js:186:1)
    at hashQueryKey (utils.js:179:1)
    at hashQueryKeyByOptions (utils.js:171:1)
    at QueryClient.defaultQueryOptions (queryClient.js:324:1)
    at QueryClient.defaultQueryObserverOptions (queryClient.js:331:1)
    at useBaseQuery (useBaseQuery.js:14:1)
    at useQuery (useQuery.js:7:1)
    at ir (index.ts:25:1)
    at Hn (index.tsx:18:1)
stableValueHash @ utils.js:186
hashQueryKey @ utils.js:179
hashQueryKeyByOptions @ utils.js:171
defaultQueryOptions @ queryClient.js:324
defaultQueryObserverOptions @ queryClient.js:331
useBaseQuery @ useBaseQuery.js:14
useQuery @ useQuery.js:7
ir @ index.ts:25
Hn @ index.tsx:18
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
(anonymous) @ notifyManager.js:75
setTimeout (async)
(anonymous) @ utils.js:323
Promise.catch (async)
scheduleMicrotask @ utils.js:322
flush @ notifyManager.js:74
batch @ notifyManager.js:30
dispatch @ query.js:392
setData @ query.js:85
onSuccess @ query.js:336
resolve @ retryer.js:58
Promise.then (async)
run @ retryer.js:116
Retryer @ retryer.js:156
fetch @ query.js:332
executeFetch @ queryObserver.js:199
onSubscribe @ queryObserver.js:40
subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157`

**Comment by ozkalai** [comment] 2022-07-27 14:09
Hey @emehmet, sorry to hear that you are having a problem. 
Does this error occur after you start the development server or while starting the development server or after you trigger something?

**Comment by emehmet** [comment] 2022-07-27 14:33
Successfully builded on development server without error. I get this error on Chrome console. I see white page. I read somethings in here. Says this is related with extensions. https://stackoverflow.com/questions/67726408/react-query-and-nextjs-fetching-data-converting-circular-structure-to-json-error

I deleted all extensions on chrome 
Also I tried  firefox(clean install) too but same error.

**Comment by omeraplak** [comment] 2022-07-27 14:41
Hey @emehmet ,
Can you confirm that you are not getting this error with an older version of refine?

**Comment by emehmet** [comment] 2022-07-28 13:41
Hi @omeraplak ,

I tried with the following versions too. But still not resolved.

```
"dependencies": {
        "@pankod/refine-antd": "3.29.0",
        "@pankod/refine-core": "3.44.0",
        "@pankod/refine-graphql": "^4.3.0",
        "@pankod/refine-react-router-v6": "^3.29.0",
        "@pankod/refine-simple-rest": "3.25.6",
        "@testing-library/jest-dom": "5.12.0",
        "@testing-library/react": "11.2.6",
        "@testing-library/user-event": "12.8.3",
        "@types/jest": "26.0.23",
        "camelcase": "7.0.0",
        "graphql": "15.5.3",
        "graphql-request": "4.3.0",
        "i18next": "20.1.0",
        "i18next-browser-languagedetector": "6.1.1",
        "i18next-xhr-backend": "3.2.2",
        "leaflet": "1.8.0",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-i18next": "11.8.11",
        "react-leaflet": "4.0.1",
        "react-leaflet-google-layer": "2.0.7",
        "react-scripts": "5.0.0",
        "web-vitals": "1.1.1"
    },
    "devDependencies": {
        "@graphql-codegen/cli": "2.9.1",
        "@graphql-codegen/introspection": "2.2.0",
        "@graphql-codegen/typescript": "2.7.2",
        "@graphql-codegen/typescript-operations": "2.5.2",
        "@graphql-codegen/typescript-react-query": "3.6.2",
        "@types/leaflet": "1.7.11",
        "@types/node": "12.20.10",
        "@types/react": "17.0.2",
        "@types/react-dom": "17.0.2",
        "nodemon": "2.0.19",
        "typescript": "4.2.4"
    },
    "scripts": {
        "dev": "nodemon --exec react-scripts start -e json",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject",
        "graphqlgen": "graphql-codegen --config codegen.yml"
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "resolutions": {
        "graphql-request": "4.3.0"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }
```

I tried on Phone's browser but same result. 
I guess this is about react-query. The react-query package you are using has been depraceted. Is it possible for you to update this? New package @tanstack/react-query.

**Comment by omeraplak** [comment] 2022-07-28 14:11
Hey,
We can't reproduce the error. It may be related to react-query. We will update soon and let you know!
I'm closing this issue, for now. Thank you 💥

**Comment by omeraplak** [comment] 2022-08-01 13:04
Hey @emehmet ,
We've created #2260 for upgrade TanStack Query. We will release soon and inform you 🏄‍♂️

**Comment by biskuvit** [comment] 2022-08-04 09:22
Hi @emehmet, we found the problem. We broke this problem while solving #2220. This issue happens when we define the custom icons in resources. A fix is found and will be released soon.

**Comment by emehmet** [comment] 2022-08-04 13:21
Hey @omeraplak and @biskuvit!

Thank you for your effort! 

I solved the problem by using the stringify function in the [flatted ](https://www.npmjs.com/package/flatted) package instead of the JSON.stringify function on the existing react-query. But due to something else, the system became very slow and I started to wait for the solution from you. 

````
utils.js:186 Uncaught TypeError: Converting circular structure to JSON
--> starting at object with constructor 'FiberNode'
| property 'stateNode' -> object with constructor 'FiberRootNode'
| property 'containerInfo' -> object with constructor 'HTMLDivElement'
--- property '__reactContainer$nnm0w6la9' closes the circle
at JSON.stringify ()
````

in utils.js I changed function from this;

```
export function stableValueHash(value: any): string {
  return JSON.stringify(value, (_, val) =>
    isPlainObject(val)
      ? Object.keys(val)
          .sort()
          .reduce((result, key) => {
            result[key] = val[key]
            return result
          }, {} as any)
      : val
  )
}
```


to 

````
import { stringify } from "flatted"

export function stableValueHash(value: any): string {
  return stringify(value);
}
````

This worked for me but I'm having performance issues. Maybe I made a mistake elsewhere. I do not know.

I think this is obsolete in react-query@4. But I am not sure.

**Comment by biskuvit** [comment] 2022-08-04 14:00
hi @emehmet, we fixed the issue you can follow from #2278. But thank you for your effort to refine 🥳

**Closed** 2022-08-04 13:59 UTC
Labels: bug

**Comment by omeraplak** [comment] 2022-08-04 15:49
Hey @emehmet 👋,
We've released @pankod/refine-core@3.56.4. Could you approve this fix?

**Comment by rassie** [comment] 2022-08-04 15:50
Hey, just stumbled over this problem, nice to see it fixed!

**Comment by emehmet** [comment] 2022-08-05 10:31
Hey @omeraplak!

Yes, it's fixed. Thank you so much 🥳👍
