### ISSUE TITLE
[FEAT] Add hover to socials in page

### ISSUE THREAD

**Issue by developer-diganta** [pankod/refine#2683] opened 2022-10-09 20:30 UTC
**Describe the bug**
Currently there is no hover effect for the socials icon on the docs page.  A hover over the icons would make it better recognizable to the user.

**To Reproduce**
1. Go to [https://refine.dev/docs/getting-started/overview/](https://refine.dev/docs/getting-started/overview/)
2. Go to footer section
3. Point to any socials icon

**Expected behavior**
A hover effect could be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/65999534/194778069-e1776dc9-985d-4176-b9ca-b98d481cb483.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 106

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**
If it seems relevant, can I work on it?

**Comment by sevkioruc** [comment] 2022-10-10 07:56
Hi everyone,
If this issue has no owner, can I take over it?

**Comment by alicanerdurmaz** [comment] 2022-10-10 08:23
Hi @developer-diganta Thanks for the issue 🙏 

We discussed with core team, and we decide this is not a bug, this is a design choice.
But we like your idea.

Do you wanna work on this issue ? 

For example:
When icons are hovered, icon color can change to brand color.

**Comment by developer-diganta** [comment] 2022-10-10 08:25
Yes! Sure would love to work on it!

**Comment by sevkioruc** [comment] 2022-10-10 08:29
Thanks @alicanerdurmaz. agreed :),
Good luck :) @developer-diganta

**Comment by AbhishekTiwari23** [comment] 2022-10-10 14:41
I am also ready to work on this with my setup. I am waiting

**Comment by alicanerdurmaz** [comment] 2022-10-11 10:22
Hi @AbhishekTiwari23 @NightHack36, @developer-diganta is already working on this issue. We can talk again if anything changes.

**Comment by AbhishekTiwari23** [comment] 2022-10-11 11:14
> Hi @AbhishekTiwari23 @NightHack36, @developer-diganta is already working on this issue. We can talk again if anything changes.

Ok, If there is any UI/UX issue, please let me know.
Thanks

**Comment by mananbansal2002** [comment] 2022-10-11 12:22
i would like to work on this issue can you please assign it to me?

**Comment by developer-diganta** [comment] 2022-10-11 16:50
@alicanerdurmaz I wanted to know how to start the server? I ran npm start but I got the error "tsup" is not recognised.

**Comment by sevkioruc** [comment] 2022-10-11 19:39
@developer-diganta Maybe it (https://refine.dev/docs/contributing/) might help you.

**Comment by alicanerdurmaz** [comment] 2022-10-12 06:38
> @alicanerdurmaz I wanted to know how to start the server? I ran npm start but I got the error "tsup" is not recognised.

@developer-diganta https://refine.dev/docs/contributing/ You can follow this guide.
You can join our [discord](https://discord.com/invite/refine) server if you want. We can answer faster on discord

**Closed** 2022-10-13 07:32 UTC
Labels: documentation, good first issue, hacktoberfest
